### ISSUE TITLE
Cell in usage.ipynb is causing hangs in doctests and ReadTheDocs

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim#1005]
The cell commands in question:
```
ds6h = xr.tutorial.open_dataset("air_temperature")
gdd = xclim.atmos.growing_degree_days(ds6h.air, thresh="10.0 degC", freq="MS")
```
Very weird behaviour: in a standard Python REPL (Python3.8 + Xarray v0.21), I get what I expected:
```
xclim.core.utils.ValidationError: Frequency of time series not strictly in ['D']. To mute this, set xclim's option data_validation='log'.
```
But when run on Jupyter, the cell is triggered to run and doesn't throw any errors, it just hangs. I've never seen this before.

_Originally posted by @Zeitsperre in https://github.com/Ouranosinc/xclim/issues/1002#issuecomment-1026954461_

**Comment by aulemahal** [comment]
After research I arrived to following discoveries:

## 1. 
The hanging operation as to do with the exception handling. In xclim, when a datachecks returns an error (the cell is supposed to raise a ValidationError because the timeseries is not daily), the ValidationError is caught by `xclim.core.utils.raise_warn_or_log`, which chooses what to do in function of the passed arguments, which come from the current options. In our case, the behaviour is to raise and it is done as:
```python3
raise err from ValueError("some message")
```
This is the line that hangs. In my current tests, I have a cell with only:
 ```
raise ValueError('what') from ValueError('wack')
```
and it hangs there.

## 2.
It only hangs in tox. I was able to recreate the bug locally by running `tox -e doctests_only`. It doesn't happen if I run `pytest` in my dev env, it doesn't happen if I run `pytest`in tox's env. It doesn't happen if I run the 3 `doctests_only` commands manually in tox's env. ONLY if I do `tox -e doctests_only`.

## 3.
There are no recent versions of pytest, nbval and tox. This only happens since  `doctests_only` uses python 3.8. It also happens when I use python 3.9. But doesn't happen with python 3.7.

## 4.
At one point I was able to interrupt the hanging call and I saw that it was stuck (at that moment) on a `os.lstat` call that seems to be done on some source file. The call was done by a function of `inspect` which was called from `pytest`.


I'm continuing my researches...

**Comment by aulemahal** [comment]
Found it!!!
It's IPython 8.0.1, which was release on jan 19th.

**Comment by aulemahal** [comment]
Ipython/ipython#12467

Damned.

**Comment by Zeitsperre** [comment]
Removing priority tag as the issue has been worked-around for the time being. Thanks, @aulemahal !
