### ISSUE TITLE
conda package

### ISSUE THREAD

**Issue by cehbrecht** [Ouranosinc/xclim#107]
### Description

A conda package would be helpful for installation ... especially in a WPS conda environment.

When xclim becomes more stable the conda package can move to conda-forge. Packages on conda-forge build automatically (if configured right) when a new pip package is uploaded.

### What I Did

I wanted to give it a start but the usual `conda skeleton` command failed ... could not find source URL:

```
$ conda skeleton pypi --noarch-python xclim
Error: No source urls found for xclim
```

See docs: 
https://conda.io/docs/user-guide/tutorials/build-pkgs-skeleton.html

I could create a conda package manually ... but I got confused by the version numbers: 0.1.0 on pypi, 0.6 on git ... no tagged version.

**Comment by tlogan2000** [comment]
@cehbrecht : to my knowledge for pypi we have not added anything other than a placeholder in order to reserve our 'xclim' package name.  @Zeitsperre would be able to give more details.  

For running/trying xclim just be aware that we are currently looking at resolving limitations in xarray for resampling with non-standard calendars.  I think it is close but the modifications have have not been submitted to the xarray package and there for a standard install of xarray would limit xclim to data with standard calendars for now

**Comment by Zeitsperre** [comment]
Creating the conda package should happen alongside #159 and #185. Once we deal with the majority of the remaining issues, we should then work on this one and the others.

**Comment by huard** [comment]
@Zeitsperre Not having regular releases makes development of downstream libraries difficult (their travis build breaks each time xclim makes an API change). Please tag and release using semantic versioning so we can plan updates of downstream components instead of having to react to them.

**Comment by Zeitsperre** [comment]
@cehbrecht 

I've been working on the staged-recipe for xclim in conda but I haven't been able to get past the same error. Perhaps I could ask you to briefly look into it? https://github.com/conda-forge/staged-recipes/pull/8382

**Comment by Zeitsperre** [comment]
@Ouranosinc/hailstorm We now have a conda package! https://github.com/conda-forge/xclim-feedstock

**Comment by tlogan2000** [comment]
> @Ouranosinc/hailstorm We now have a conda package! https://github.com/conda-forge/xclim-feedstock

Good job TJ!
