### ISSUE TITLE
Speed up CI checks by splitting dedicated documentation and upstream builds ?

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim#1155]
### Addressing a Problem?

Xclim has many dependencies that are heavily tested, and runs some fairly advanced examples in the notebooks on every build. Sometimes this means CI checks run for 20+ minutes on each commit. This is a lot of computing time spent on every commit.

### Potential Solution

Assuming a pull request doesn't introduce breaking changes to the existing tools (different call signatures, different expected results, etc.), the notebooks at least should remain valid between commits and PRs. Upstream dependencies are meant for us to be aware of upcoming changes, so focused PR contributions shouldn't need to worry about this level of support.

I would like to see us using sphinx-autodoc import mocking and only running the notebooks as-needed (i.e. if breaking changes are introduced). I also think upstream dependency checks should be run on the trunk. There are a few ways that we could do this:

1. We patch `docs/conf.py` in a GitHub Action to mock imports when the branch is not `master`.
2. We investigate whether there is a way to have a toggle-able configuration within the PR that only starts building with real dependencies and running notebooks when marked.
3. (Maybe overengineered) We dedicate a `dev` branch that PRs are expected to push to. This branch will then run heavier CI tests and can be modified directly, as-needed. On success, we push to master (`latest`).

In all case, I think we should move upstream-related tests to only run on push to `master`/`dev`.

### Contribution

- [X] I would be willing/able to open a Pull Request to contribute this feature.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aulemahal** [comment]
Not totally related to documentation builds, but maybe we could merge the "test-py38-opt-slow-conda" and "py39-slow-lm3" builds?

We'd have:
- test-py38-upstream-dev-dependencies : Python 3.8, and some dependencies at master
- test-py39-opt-slow-conda : Python 3.9, slow tests and optional dependencies (sbck, lm3, eofs)
- test-py310 : Python 3.10.

Sadly, we can't divide "opt" and "slow". So that is one test lest, but given they run in parallel, it's not really accelerating the builds, simply using less github minutes...
