### ISSUE TITLE
non-optional optional argument "lat" for xc.indices.cool_night_index(tasmin: )

### ISSUE THREAD

**Issue by christian-stepanek** [Ouranosinc/xclim#1179]
### Setup Information

- Xclim version:   0.37.0
- Python version:  3.9.12
- Operating System:  ubuntu linux 20.04.5, 5.14.0-1051-oem, x86_64

### Description

The input array "lat" is considered optional in the documentation, yet if that input array is not given then xc.indices.cool_night_index drops an error:

```TypeError: cool_night_index() missing 1 required positional argument: 'lat'```

Also the source code does not indicate that lat should be considered optional as there is no fallback setting that becomes active if lat is not given.

This may be either a problem of the implementation or of the documentation.

### Additional context

Making the input of lat optional via changing
```tasmin: xarray.DataArray, lat: xarray.DataArray, freq: str = "YS"```
to
```tasmin: xarray.DataArray, lat: xarray.DataArray | None = None, freq: str = "YS"```
should be programmatically straightforward I believe, but I do not know whether that is scientifically sensible in this case.

### Contribution

- [X] I would be willing/able to open a Pull Request to address this bug.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aulemahal** [comment]
Woups indeed! The way the indice is currently coded means `lat` is not optional and the doc should reflect that.

However, in other recent indices, we have added `cf_xarray` as a dependency to xclim. Using this, we could at least try to guess which coordinate of `tasmin` is the latitude when `lat` is not explicitly given.

**Comment by Zeitsperre** [comment]
Hi @christian-stepanek, you're right that the docstring is misleading.

As the indice is currently coded, `lat` is non-optional. Given that `lat` is only used as a switch to determine the month to examine in the tasmin time series, We could potentially support a default string variable (e.g. `"north"`, `"south"`) so that users can arbitrarily set a `lat` for their data. This would be useful gridpoint arrays without latitude, but that's a very specific use case.

I like @aulemahal's suggestion to use `cf_xarray` though. This should be quick to address. A fix will be available soon.

**Comment by christian-stepanek** [comment]
Thanks a lot to @Zeitsperre and @aulemahal for your quick response. And to all developers for providing a great toolbox to the community!!!

This here seems to work without any obvious problem:
```
import xarray as xr
import xclim as xc
import numpy as np
df_tasmin = xr.open_dataset(t2min.nc').data_vars["t2min"]
cool_night_index=xc.indices.cool_night_index(tasmin=df_tasmin,lat=df_tasmin.lat)
```
Then one could just use as a fallback the latitudes that come with the dataset, am I right? At least to me it also feels natural to use the latitudes for which the data is given.

**Comment by aulemahal** [comment]
Indeed! This is the essence of what I am suggesting. However, we don't want to _assume_ that the coordinate is named "lat", because even though it is very common, it is not prescribed by any standards xclim follows. Which is why we would use `cf_xarray`, because we already follow the CF conventions in many places.

It would then look like:
```python3
import xarray as xr
import cf_xarray
import xclim as xc

ds = xr.open_dataset('t2min.nc')
cool_night_index = xc.indices.cool_night_index(ds.tasmin, lat=ds.tasmin.cf['latitude'])
```
Assuming that dataset has set a minimum number of attributes to it's latitude coordinate, allowing `cf_xarray` to detect it.
