### ISSUE TITLE
The `opt-slow-mamba` build is hanging on GitHub Actions

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim#1238]
### Setup Information

- Xclim version: 0.39-dev
- Python version: 3.9
- Operating System: Linux

### Description

This particular build has been hanging when examining the Actions. In some cases, the build is hanging for literally hours for some reason. It looks as though issues started on November 11, 2022. 

The test that might be causing this issue is `xclim/testing/tests/test_sdba/test_properties.py::test_first_eof`. I imagine this might be due to a conda-forge package update.

### Additional context

https://github.com/Ouranosinc/xclim/actions/runs/3447286516/jobs/5753477393#step:6:3076
https://github.com/Ouranosinc/xclim/actions/runs/3447627488/jobs/5753842536#step:6:3076

### Contribution

- [X] I would be willing/able to open a Pull Request to address this bug.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aulemahal** [comment]
I have no idea what is going on... On my machine everything runs smoothly. `eofs` hasn't been update in 3 years and I tested with both the latest and previous versions of xarray...

Also the github action logs is quite unclear... "canceled"? Is it a memory issue? Doesn't look like a timeout since there's one build canceling after 58 mn and the other after 36 mn...

**Comment by Zeitsperre** [comment]
The cancelling was done by me. It shouldn't be running for more than 20 minutes.

**Comment by aulemahal** [comment]
Oh! I see. I'll push a PR soon where I simply reduce the size of the test data, we'll see.

**Comment by Zeitsperre** [comment]
It seems to be back: https://github.com/Ouranosinc/xclim/actions/runs/3623422994/jobs/6109646934#step:7:2971
