### ISSUE TITLE
windows_run_count ignores freq when ufunc_1dim=True

### ISSUE THREAD

**Issue by cuell** [Ouranosinc/xclim#1279]
### Setup Information

- Xclim version: 0.40.0
- Python version: 3.10
- Operating System: Ubuntu 22.04

### Description

When ufunc_1d is selected, windows_run_count outputs the total number of contributions to a run, regardless of whether or not freq is specified

### Steps To Reproduce

```
import xarray as xr
import xclim


def bug_windowed_run_count():
    da = xr.DataArray([False] * 730, dims=['time'], coords={'time': xr.date_range('2001-01-01', '2002-12-31')})
    da[10:20] = True  # 10 days in 2001
    da[400:420] = True  # 20 days in 2002
    wrc = xclim.indices.run_length.windowed_run_count(da, window=3, freq='YS')

    # expected [10, 20]
    # actual 30
    return wrc

```

### Additional context

It looks like it's a minor logic error in `windowed_run_count()`, where resampling doesn't happen if `ufunc_1dim == True`

```
    if ufunc_1dim:
        out = windowed_run_count_ufunc(da, window, dim)

    elif window == 1 and freq is None:
        out = da.sum(dim=dim)

    else:
        d = rle(da, dim=dim, index=index)
        d = d.where(d >= window, 0)
        if freq is not None:
            d = d.resample({dim: freq})
        out = d.sum(dim=dim)
```

### Contribution

- [ ] I would be willing/able to open a Pull Request to address this bug.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coxipi** [comment]
Thanks for reporting this. 

# The bug
The behaviour was intended, but you were not notified about it because there's an error in the code. In  `windowed_run_count`, we currently have:
```
ufunc_1dim = use_ufunc(ufunc_1dim, da, dim=dim, index=index)
```
but there should be an extra argument `freq=freq`. The combination `ufunc_1dim==True` and a defined `freq` (not `None`) would raise a value error in `use_ufunc`, stating that 
>  Resampling after run length operations is not implemented for 1d method

# A possible computation with the current `xclim`
To get a similar behaviour to what you want, you can first resample your data, then map to the function `windowed_run_count`:
```python
from xclim import run_length as rl
window = 3
freq = "YS"
da.resample(time=freq).map(rl.windowed_run_count, [window], ufunc_1dim=True)
```
or simply use the function `resample_and_rl` with `resample_before_rl=True`. This function is in `run_length.py`. Many indices use this function, for instance `maximum_consecutive_wet_days` in `_threshold.py. 

This can lead to differences however, because resampling is done before the `windowed_run_count`.

# To enhance or not
Why not implement `resample_before_rl=False` for the 1d version too?

The 1d version of `run_length` and `windowed_run_count` in this case was a workaround to alleviate some performance issues (in some specific cases) of regular multi-dimensional algorithms using `xarray`. Those issues were solved in #1134 , which allowed the new behaviour, i.e. resample after using run length introduced in #1136. This new feature was not implemented to the 1d algorithm because as far as I could tell, performance benefits of the 1d version algorithm in some specific were now marginal or non-existent. 

If you still have performance justifications to keep using the 1d algorithm, I'd be interested to know more about it!
