### ISSUE TITLE
Drought indices

### ISSUE THREAD

**Issue by Balinus** [Ouranosinc/xclim#131]
Drought indices from the source @huard pointed me is now developing an xarray interface. Might be useful to keep an eye on it.

See https://github.com/monocongo/climate_indices/issues/191

**Comment by monocongo** [comment]
This effort is somewhat stalled, as I discovered limitations when using dask that seem to prevent its use internally (i.e. I'd need to pull out numpy arrays in order to do several things that you can't do using dask, such as indexing individual array elements using integer array indices, etc.). See [this](https://stackoverflow.com/questions/52933553/dask-assignment-error-when-updating-a-value-in-a-dask-array-using-typical-numpy) and [this](https://stackoverflow.com/questions/53292792/dask-equivalent-of-numpy-convolve-hstack) for some of the details.

I'll be happy to pick this up again, as I'd like to be able to leverage dask for larger input datasets, as well as making the library easier to integrate into xclim (if that's the intention here). It's just not clear how I can get there from here -- apparently my xarray/dask-fu is still weak.

BTW I ended up getting much better performance using vanilla multiprocessing mapping of `numpy.apply_along_axis` rather than `xarray.apply_ufunc`, but there may be something obvious I'm missing there. See monocongo/climate_indices#210 for details.

**Comment by aulemahal** [comment]
@huard  @tlogan2000  Is this a library that would be interesting to have as a dependency and wrap into indices/indicators? Or should we reimplement the indices so that they make use of xarray/dask and follow our standards (instead of numpy/numba)?

**Comment by monocongo** [comment]
If this ball gets rolling I'll be happy to help where I can. My current processing scripts utilize a complicated shared memory solution which I'd love to replace with something more elegant by leveraging xarray and/or dask, so if you guys have good ideas I'd love to piggyback on it (my xarray/dask-fu is still weak).

**Comment by huard** [comment]
I think this would certainly be a valuable addition, but looking at the original code, probably not a trivial task. Before we jump into this, I suggest we make sure that
1. We have identified potential users
2. James has some free time to help us out
3. We have enough free cycles to do a good job.

**Comment by tlogan2000** [comment]
In terms of projects / users asking for indices to my knowledge we have only SPEI so far (I believe PET would needed as a sub calculation though).  

So we could maybe look at implementing this single calculation to start with?  FYI We are using environment canada SPEI datasets (already calculated) for current needs so there is no real urgency to have this done in the short-term

**Comment by monocongo** [comment]
The computations aren't too tricky, but doing them in parallel has been surprisingly challenging for me. Each computation (SPI, PET, SPEI, etc.) is done on a time series, i.e. a 1-D array, for a location (typically a lat/lon point). So it's essentially a question of doing something like this, but in a more elegant fashion:
```
# input data array with shape (lats, lons, times)
lats, lons, _ = data.shape
indices = np.array(data.shape, dtype=float)
for lat in lats:
    for lon in lons:
        timeseries = data[lat, lon]
        indices[lat, lon] = compute_index(timeseries, other_params)
```
I have tried doing "split-apply-combine" with xarray.GroupBy and cooking up ufuncs for use with numpy.apply_over_axes, etc. but to no avail, hence my current Frankenstein approach where I've cooked up shared memory arrays to facilitate parallelization with multiprocessing. You guys are probably a lot better at this than I am and can maybe come up with a better solution, and if you do I'll be eager to cook it into my processing scripts to get away from the current complexity therein.

As far as having some time to help with this I do have a bit, but my day job does keep me busy so I want to set reasonable expectations. This is purely a labor of love for me these days to indulge the wannabe scientist in me. Fortunately, the package does seem to be getting some use outside of NOAA, most recently I was made aware that it is being used in [a training by NASA](https://www.youtube.com/watch?v=Gok9zsA_RFk).

**Comment by huard** [comment]
We have another similar case with fire weather indices. It's original fortran code, translated into python, then wrapped by numba and numpy. See #388  I suspect a similar strategy would work here. 

Got it, we appreciate the dedication !

**Comment by huard** [comment]
From #973
> It would also be convenient to add some drought indices. This package is useful: https://climate-indices.readthedocs.io/en/latest/
> 
> The code can be called outside the command line and be made to work with apply_ufunc as in: https://github.com/mintproject/droughtIndices/blob/d1149ba63f275b5a4531fbd6a6cadefaef90ecc2/WM_climate_indices.py#L369
