### ISSUE TITLE
some more climate indicators

### ISSUE THREAD

**Issue by ludwiglierhammer** [Ouranosinc/xclim#1352]
### Addressing a Problem?

Hi guys,

I would like to implement some more climate indicators:

- mean_precipitation: `mean(dim="time")` instead of `sum(dim="time")`; see [precip_accumulation](https://xclim.readthedocs.io/en/stable/_modules/xclim/indices/_multivariate.html#precip_accumulation)
- snowfall_frequency: see `Sfreq` in [Frei P., 2016](https://www.meteoswiss.admin.ch/dam/jcr:2695424d-351a-47ab-8da3-696a6870225b/SR101_Frei.pdf)
- snowfall_intensity: see `Sint` in [Frei P., 2016](https://www.meteoswiss.admin.ch/dam/jcr:2695424d-351a-47ab-8da3-696a6870225b/SR101_Frei.pdf)
- dry_spell_max_length: according to [hot_spell_max_length](https://xclim.readthedocs.io/en/stable/_modules/xclim/indices/_threshold.html#hot_spell_max_length)
- mean_daily_wind_speed: see `FG` from [ECA&D indices](https://www.ecad.eu/indicesextremes/indicesdictionary.php#9)
- maximum_daily_maximum_wind_speed: see `FXx` from [ECA&D indices](https://www.ecad.eu/indicesextremes/indicesdictionary.php#9)
- delayed_frost_days: we can use something like [frost_days](https://xclim.readthedocs.io/en/stable/indices.html#xclim.indices.frost_days) but with a `before_date` as in [last_spring_frost](https://xclim.readthedocs.io/en/stable/api.html#xclim.indicators.atmos.last_spring_frost). Is there already a function implemented in `xclim` whihc differentiate between the Northern and the Southern hemisphere? Let's say a `delayed_frost_day` at the Northern hemisphere is a frost day between the 1st of April and the 31st of June and a `delayed_frost_day` at the Southern is a frost day between the 1st of October and the 31st of December (random dates; just to illustrate)
- precpitation_amount_from_wet_days_above_threshold: Total precipitation amount with precipitation > {perc}th percentile on wet days (precipitation >= 1 mm)
- precpitation_fraction_from_wet_days_above_threshold: Precipitation fraction with precipitation > {perc}th percentile on wet days (precipitation >= 1 mm)

In addition I want to implement a conversion from a snowfall flux in `kg/m**2*s` to a snowfall flux in `m/s` and vice versa according to [snw_to_snd](https://xclim.readthedocs.io/en/stable/_modules/xclim/indices/_conversion.html#snw_to_snd). This conversion could be used in `snowfall_frequency` and `snowfall_intensity`. Input variable is `prsn`.

To calculate percentiles I only found [percentile_doy](https://xclim.readthedocs.io/en/stable/_modules/xclim/core/calendar.html#percentile_doy). Is there a way to calculate the `percentile_of_the_year`?

Are you intersted in some of those implementations? If so should I create one PR or multiple ones like
- PR1: `snowfall_frequency`, `snowfall_intensity` and `snowflux_converation`
- PR2: `mean_daily_wind_speed` and ` maximum_daily_maximum_wind_speed`
- PR3: `delayed_frost_days`
- PR4: `precpitation_amount_from_wet_days_above_threshold`, `precpitation_fraction_from_wet_days_above_threshold`  and `percentile_of_the_year`
- PR5: `dry_spell_max_length`
- PR6: `mean_precipitation`

Cheers, Ludwig

### Contribution

- [X] I would be willing/able to open a Pull Request to contribute this feature.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Zeitsperre** [comment]
Hi @ludwiglierhammer

I can't speak to the `percentile_of_the_year` calculation (ping @aulemahal), but for the indicators you mentioned, if you want to contribute those, I would be all for it. We can handle the code verification, French translations and help out as needed.

Thanks again!

**Comment by aulemahal** [comment]
Nice! We are certainly interested in adding indicators, especially if they come from PRs outside of the Ouranos core team!

A few comments.

For the "snow fall flux" to "snow fall rate" conversion, we recently added something along the same lines directly in the `xclim.core.units` submodule. See [`amount2lwethickness`](https://xclim.readthedocs.io/en/stable/xclim.core.html#xclim.core.units.amount2lwethickness). However, this gives the liquid water equivalent. Indeed, if you meant the actual depth, needing the density, a new function could be useful.  We have a goal to refactor the whole "variable conversion" functions, but we haven't done anything yet.

Another midterm goal is to have an easier mechanism for very simple indicators. I.e.: skip the indice-indicator duality by implementing something like a "mean_precipitation" indicator (I would rather name it "pr_mean") by wrapping a generic function into an indicator directly. I have yet to take time to implement this. I feel the 6 first indicator you mention would be super easily implemented with such a mechanism...

Personally, I would prefer names based on the variable names. We haven't decided for a systematic naming convention yet, but I think names like "prsn_mean" and "sfcWindmax_max" could be better ?

We do not have a special function to handle hemisphere-dependent computation, but we did encounter this issue. For example in [`cool_night_index`](https://github.com/Ouranosinc/xclim/blob/1966c0f8bb6bdeceb97bc7a70fc5f4eb8121be1b/xclim/indices/_agro.py#L450). If you're able to have something generic that would be interesting! Otherwise, it's not a problem if it is specific to your indicator.

What do you mean by `percentile_of_the_year` ? The percentile of each given day within the distribution of the whole year? Like, `pr.resample(time='YS').apply(lambda pryr: pryr.rank('time') * 100)` ? It could be useful, maybe named `percentile_within_year` ? Or even, `percentile_within_period` with a customizable `freq` arg ?

As for your implementation plan, it looks good. I think you could merge PR1, PR2 and PR6. All those indicators are simple wrappers of simple generic functions.

Héhé I hope my lengthy comment is not discouraging you :sweat_smile: !

**Comment by ludwiglierhammer** [comment]
Super! Thanks for your fruitful comments. Now, I am super couraged :smile: ! I'll give it a try and you'll see my progresses in new PRs. 

By`percentile_of_the_year` I mean one percentile value over the entire reference period. For instance, `percentile_doy` yields one percentile value for each day of the year and `percentile_of_the_year` would yield only one percentile value over the entire input period. I hope this is more understandable now. We at [GERICS](https://gerics.de/) often use this kind of percentile value for calculating climate percentile indicators (e.g. tg90p). And yes, I think we need another name for it. Your `percentile_within_year` sounds interessting too. Maybe we could implement both.

**Comment by ludwiglierhammer** [comment]
Could we expand [maximum_consecutive_dry_days](https://xclim.readthedocs.io/en/stable/_modules/xclim/indices/_threshold.html#maximum_consecutive_dry_days) with the parameter `window` (see [hot_spell_max_length](https://xclim.readthedocs.io/en/stable/_modules/xclim/indices/_threshold.html#hot_spell_max_length)) to get `dry_spell_max_length`? The codes are very similar.

Should we implement a new indicator called `dry_spell_max_length` or expand `maximum_consecutive_dry_days` or expand `maximum_consecutive_dry_days` and rename it to `dry_spell_max_length` (for compatibility reasons) ?

**Comment by Zeitsperre** [comment]
Everything seems to be in the right place. Closing.
