### ISSUE TITLE
Send a warning if calculating indicators after dropping dates with `convert_calendar`

### ISSUE THREAD

**Issue by SarahG-579462** [Ouranosinc/xclim#1410]
### Addressing a Problem?

When using `convert_calendar` and moving from, for example, `"leap"` to `"360-day"`, many dates are dropped. If calculating indicators after this, this will introduce bias. indicator calculation before `convert_calendar` will result in different output than after `convert_calendar`. For example, if the dropped date is above the heat wave threshold, it will bias heat wave calculations. 

This is likely unintended behavior for most users, so should be warned against, unless they know what they're doing.

### Potential Solution

When `convert_calendar` drops a date, e.g. from `noleap` to `360`, or from `leap` to `noleap`, a flag should be set in the dataset. Subsequent indicator calculations should warn the user that some dates were previously dropped, which may bias the results of the indicator calculations. Indices calculations, I think, don't need to check for this warning. 

### Additional context

- [ ] Should be able to suppress this warning, either during convert_calendar, or during indicator calculations?
- [ ] When doing ensemble calculations, e.g. with xscen, is the bias introduced worth the consistency in calculation across mixed calendars?

The opposite, when going from 360 to noleap, for example, will be checked by the indicator health checks (e.g. [missing value identification](https://xclim.readthedocs.io/en/stable/checks.html#missing-values-identification)), and so shouldn't be problematic. 

### Contribution

- [X] I would be willing/able to open a Pull Request to contribute this feature.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aulemahal** [comment]
Isn't the indicator already simply failing ? For example, when going from noleap to 360_day, a subsequent indicator call would give : `ValidationError: Frequency of time series not strictly in ['D'].`. In this case, that's because the 29 and 30th of Feb are missing.

| Cal in  | Cal out | ValidationError |
|----------|------------|-----------------------|
| noleap | leap | yes |
| noleap | 360 | yes |
| leap | noleap | no |
| leap | 360 | yes |
| 360 | leap | yes |
| 360 | noleap | yes |

(by "leap" I mean a leap year in a standard cal, by "noleap" I mean a not-leap year in a standard cal, or a noleap cal)

My point here is I would argue that :
- if you are silencing the error one way or another, then we assume you know what you're doing
- if you are fixing your timeseries by inserting days where missing, then we assume you know what you're doing

Also, but that may be an even more personal view: if you are using "convert_calendar", I don't think the dropping of now-invalid timesteps is "unintended behavior". That's the point of the method.

A final technical caveat: xclim's convert calendar is a superset of xarray's. In 90% of the cases, xarray's is good enough. If we add a flag in xclim, chances are we would miss many cases where xarray's `convert_calendar` was used instead. I don't know who uses which though.

----

On the other hand, if we add this, I wonder if we could pass the information through the `history` attribute ?

**Comment by SarahG-579462** [comment]
That's a very good point, I forgot about feb 29 and 30 being missing from 360-day. It's still an issue for leap->noleap, though, and if the user uses the `missing=` option.  

> Also, but that may be an even more personal view: if you are using "convert_calendar", I don't think the dropping of now-invalid timesteps is "unintended behavior". That's the point of the method.

Agreed, the unintended behaviour is the introduction of bias when computing indicators, which is a side-effect of dropping days which users might not be aware of.

> A final technical caveat: xclim's convert calendar is a superset of xarray's. In 90% of the cases, xarray's is good enough. If we add a flag in xclim, chances are we would miss many cases where xarray's convert_calendar was used instead. I don't know who uses which though.

Hm, one day it might be nice if we could do `ds.xclim.indicators.atmos.relative_humidity`, e.g.,  like rioxarray does. At that point, maybe we could subclass Dataset to call super().convert_calendar, and append the flag then. In the meantime though, I don't see an easy solution here.
