### ISSUE TITLE
xclim.indices.standardized_precipitation_index() return infinite values

### ISSUE THREAD

**Issue by JavierDiezSierra** [Ouranosinc/xclim#1416]
### Setup Information

- Xclim version: 0.39.0
- Python version: 3.8.13 
- Operating System: Ubuntu 22.04.02

### Context

The standardized precipitation index function returns infinite values (np.inf) for some time periods in which the precipitation is maximum or minimum (see Figure). The input data (dataset_pr.pr) does not have any nan or fill/missing value. 

It seams that the function can not deal with some precipitation thresholds (maximum and minimum).

I am using the following code:

```
dataset = standardized_precipitation_index(
        pr=dataset_pr.pr,
        pr_cal=dataset_pr.sel(time=slice(datetime(1971, 1, 1), datetime(2010, 12, 31))).pr,
        freq="MS",
        window=6,
        dist="gamma",
        method="ML",
    )
```
Thank you very much in advance for the help.

![Screenshot from 2023-07-07 13-11-54](https://github.com/Ouranosinc/xclim/assets/32273213/5ffdf8e8-54e4-4491-bf34-e46d09fe7de7)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coxipi** [comment]
Hi @JavierDiezSierra, thanks for the report. 

Are those points always np.inf at any time slice, or only this particular one? 

As you observe, this happens in locations where the value of SPI is extreme. A value of SPI beyond ±3.09 with a sample size less than 100 will likely be irrelevant statiscally according to [Guttman, 1999](https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1752-1688.1999.tb03592.x).  I'm suspecting the problem is in the fitting of gamma distribution parameters using the "ML" method. 
Could you try running the approximate method "APP" to see if the np.inf remains? In the case of the gamma distribution,  "APP" solves the maximum likelihood with a saddle point approximation (e.g. eq.22 in [Thom, 1958](https://journals.ametsoc.org/view/journals/mwre/86/4/1520-0493_1958_086_0117_anotgd_2_0_co_2.xml?tab_body=pdf) ). This is method is also used in the [climate indices library](https://github.com/monocongo/climate_indices)

If you could share one time series at a given problematic lat/lon, or tell me what data you are using, that could be helpful.

**Comment by JavierDiezSierra** [comment]
Thank you very much @coxipi for your quick response. 

> Are those points always np.inf at any time slice, or only this particular one?

The points are np.inf in this particular time slice.

> As you observe, this happens in locations where the value of SPI is extreme. A value of SPI beyond ±3.09 with a sample size less than 100 will likely be irrelevant statiscally according to [Guttman, 1999](https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1752-1688.1999.tb03592.x). I'm suspecting the problem is in the fitting of gamma distribution parameters using the "ML" method.

What do you mean with 100 sample size?. My precipitation data has daily resolution and it covers the period 1970-2060. I am using the period 1971-2010 as baseline period for the calibration. I understand correctly, xclim resamples the data to monthly aggregation and then the index is calculated with a rolling mean of 6 months in mi case (spi6), which means that my calibration period has (2010-1971)*12 = 468 samples.

> Could you try running the approximate method "APP" to see if the np.inf remains? In the case of the gamma distribution, "APP" solves the maximum likelihood with a saddle point approximation (e.g. eq.22 in [Thom, 1958](https://journals.ametsoc.org/view/journals/mwre/86/4/1520-0493_1958_086_0117_anotgd_2_0_co_2.xml?tab_body=pdf) ). This is method is also used in the [climate indices library](https://github.com/monocongo/climate_indices)

With the "APP" method I still get some np.inf values, but in different cells location and times. 

> If you could share one time series at a given problematic lat/lon, or tell me what data you are using, that could be helpful.

Here you can find the file I am using: https://drive.google.com/drive/folders/1021xvVW3zlNgFoqw7mfv4vy1mhesojck?usp=sharing

Thank you very much in advance for the help.

**Comment by coxipi** [comment]
> What do you mean with 100 sample size?

My interpretation was the same as yours, but I would consider each month  as a  separate series, so I would not multiply by 12 and would say there is  39 data points on for each month/lat/lon to fit the gamma distribution. 

Re-reading the relevant part from the paper, I'm not entirely sure this is the correct interpretation:

> Theoretically, the SPI is unbounded. Practically, the number of observations of the precipitation data, which is generally less than 100 for a given month, season or other time period, for locations in the United States, suggests bounds of ±3.09. These bounds correspond to probabilities of .999 and .001 and return periods of one in 1,000. Estimation of more extreme probabilities, based on sample sizes of only 100, is likely to be inaccurate.

I will reconsider this point later if necessary.  Also, just to confirm
> xclim resamples the data to monthly aggregation and then the index is calculated with a rolling mean of 6 months in mi case (spi6)

That's correct!

I also get the "turtle with its egg" in the bottom left, so I will see what is going on here:
![image](https://github.com/Ouranosinc/xclim/assets/71575674/d9ae15ec-1dff-480e-ad7c-1604ef05a051)

I have 0.1% of ±inf spi values for the whole time period in the small region I showed, but when using "APP", no infinities. Very extreme spi values with "ML" are also less extreme with "APP".
![image](https://github.com/Ouranosinc/xclim/assets/71575674/204cce16-43a9-477c-a9e9-3b63f002ef3a)

 Anyways, I will dig this more next week.

**Comment by JavierDiezSierra** [comment]
Many thanks for your time and effort. 

I would just like to add one more thing. Using the "APP" method I obtain also inf spi values in a different month and location (see Figure)

![Screenshot from 2023-07-08 10-27-40](https://github.com/Ouranosinc/xclim/assets/32273213/110d02c3-aa71-4a5e-94df-d59a81b3a5a5)

**Comment by coxipi** [comment]
Ok, I found the issue. It is related to extreme values in spi indeed.

When transforming a precipitation value to a normalized index, we first evaluate how probable a given value is in comparison to the calibration data. This is done by computing:
```python
prob = scipy.stats.gamma.cdf(some_value, **fit_params)
```
So, `prob` is the probabilty that a value in a pdf with `fit_params` would produce a value below `some_value`. Then, this is transformed back to the normal distribution with 
```python
spi = scipy.stats.norm.ppf(prob)
```
What happens is that for very extreme values, `scipy.stats.gamma.cdf(some_value, **fit_params)` gives either `1.0` (very wet) or `0.0` (very dry) instead of, say, `0.9999999...9` and `0.00000...01` because `scipy.stats.gamma.cdf` has precision limitations. When using exactly 0.0 or 1.0 in `scipy.stats.norm.ppf`, this when we get ±np.inf. I saw this exact behaviour for the white spots in both cases you mention. For the "APP" case, I also confirmed that the results in general match those obtained  with https://github.com/monocongo/climate_indices (computes an SPI, among other things, with the "APP" method). 

The most precise value I could get with a float64 is: `0.9999999999999999` which gives a spi of `8.209536151601387`, it seems indeed to be the maximum values non-"inf" you obtained in your plot above. 

I think it could be good to add a warning when this kind of issue happens. But as I was mentioning earlier, this is not only a numerical issue, but a statistical one: Very extreme values of spi should be taken with a grain of salt given a limited sample size. 

For now, you could simply take this numerical limitation as a cutoff value
```
spi = spi.clip(-8.21,8.21)
```
everything above 8.21 will be taken back 8.21, etc.

**Comment by JavierDiezSierra** [comment]
The fact is that we are applied massively the spi and spei funtions from xclim to most of the CMIP6 and CORDEX simulations available and we found that this issue occurred in several simulations and periods.

I really appreciate you help. Thank you VERY much.
