### ISSUE TITLE
`degree_days_exceedance_date` nans cause issue on climatedata.ca

### ISSUE THREAD

**Issue by juliettelavoie** [Ouranosinc/xclim#1459]
### Generic Issue

If the input to `degree_days_exceedance_date` never reaches the `sum_thresh`, the output is `nan`.
This makes sense when a user is using this function on a single input.
However, when you do the calculation on different models and then calculate the ensemble stats, it can lead to issues.
If half the models never reach the threshold they will be ignored in the ensemble stats and the results will be biased too early.
For people using xclim directly, it is not so bad as they can just add a manual check (though it would be nice to have a warning), but it is worst when the function is used on the Analyze page of climatedata.ca.
People using the website only get the percentiles output and have no idea how many models were actually included in the ensemble. The intermediate data is invisible to them.

I'm not sure how to fix this. 
In my project, I manually set the nans to be at a specific day that make sense in my context. ( I am looking for date when ice roads season begins. I set the nans to the date of the end of the ice roads season, march 31st.)
Maybe this could be a new argument, `missing` or `never_reached` ?
Maybe just a warning that the threshold is not always reached is sufficient?
Maybe ensemble stats  can have a warning when there are nans ?
 
 Though, I don't really know how to transfer those warning to climatedata users.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aulemahal** [comment]
As usual, one issue is that xclim can't warn because the computation is lazy... Same thing for the ensemble stats.

I think would prefer implementing the solution for this issue in `finch`, rather than here ? Finch could detect that doys are being used in the ensembles stats and `fillna` with something ?

But indeed, having a `never_reached` in xclim would allow the distinction between a real NaN (from missing values) and a non-reached value. If we go with this option, we could try to make it usable to all doy indicators where this is an issue. (Not sure if there are any others though).

**Comment by huard** [comment]
What about setting the value to -999 ?

**Comment by juliettelavoie** [comment]
-999 could be a default value for `never_reached`, but it would not fix the issue on the climatedata.ca Analyze page. 
If only somes models of the ensemble never reach the threshold, their number would just mess up the median and ignoring it just does the same as a nan.

**Comment by huard** [comment]
Right, sorry I forgot that part. 

Let't brainstorm about possible options.

1. Set the default value for non-exceedance to the end of the period. This would still affect ensemble statistics, because it would not reflect the real rate at which simulations approach the exceedance value. 
2. Extrapolate. That is, find the rate at which we approach exceedance and extrapolate the DOY at which it would happen if the year continued. This neglects seasonal cycles, so would give weird results if we're far from reaching the threshold.
3. Replay the same year. Repeat the same year over and over until you reach the threshold, so you could get a DOY of 450. Changes the interpretation of statistics, so needs to be clearly communicated. 
4. Exclude values from ensemble computation. We just need a marker value, other than NaN, to mark these simulations and mask them when computing stats. Ideally, those results would be presented as well using a different visual presentation. 

My feeling is that xclim needs to communicate clearly that the threshold value was not reached. The question of how to compute ensemble stats is separate, and I don't think it can be solved by xclim itself, because there's a judgement call to make by the analyst. In climatedata.ca, the results from those computations aren't displayed, right? You'll get the CSV and then will be responsible to compute ensemble stats?

**Comment by juliettelavoie** [comment]
No, the ensemble stats is done by climatedata. You get a csv with colums: 
` lat | lon | time | scenario | degree_days_exceedance_date_p10 | degree_days_exceedance_date_p50 | degree_days_exceedance_date_p90`

There is no way of knowing if models were included or not in the ensemble.

**Comment by huard** [comment]
Beh... this is problematic.

**Comment by juliettelavoie** [comment]
Thoughts on your ideas based on my case study (ice roads can start to be built at 380FDD from oct. 1st). 

2. This doesn't really make sense in this case. It would assume that the freezing in march continues as it did in february.
3. This doesn't work here. As temperature rise in spring, we would only reach the threshold next november or so. That doesn't really make sense.

**Comment by huard** [comment]
I'd argue that 1. is not much better... 

I'd go with 4 at the xclim level, and then think how to spit out something meaningful for climatedata.ca within finch, as Pascal initially suggested.

**Comment by juliettelavoie** [comment]
1 is flawed for sure, but I think it can be a lesser evil for some application where the user decision will remain the same after a given date (eg. not building the ice road at all).

 A `never_reached` arg default could be -999, but also accept DD-MM strings. But, I don't think it is absolutely necessary to xclim.
 
 one idea for finch: we could add a column with number of member used in the ensemble calculation ?

**Comment by huard** [comment]
Seems reasonable.

**Comment by juliettelavoie** [comment]
This was discussed in the CCDP data working group yesterday.
One of the solution proposed was to only give a number when a given percentage of models have reached the threshold and to point users to download the results per model (CRIM is working on that feature).

Laura also wrote this: "An imperfect solution: If you could select a season end date, you could provide the output as "countdown" or length of season? The ice road starts zero days before the end of season? The ice roads season is 0 days long?"

**Comment by aulemahal** [comment]
First solution is interesting, to be done in finch or higher.

Laura's solution is actually pretty good. If you are using `degree_days_exceedance_date` as a proxy for the actual indicator you're trying to compute, why not implement that indicator directly instead ? Doing that gives a better control for a indicator-specific handling of the "never_reached" case.

**Comment by tlogan2000** [comment]
Wouldn't solution 2 possibly make sense in `xclim.ensembles`?  Something similar to the `min_periods` param in `xr.rolling` .

**Comment by aulemahal** [comment]
Indeed, that would make even more sense!
