### ISSUE TITLE
Speed up doc builds

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#1470]
### Addressing a Problem?

Compiling the documentation takes a really long time. Makes debugging math equations really painful. 

### Potential Solution

myst-nb has options to cache the notebooks. 

### Contribution

- [ ] I would be willing/able to open a Pull Request to contribute this feature.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Zeitsperre** [comment]
See also #1439

**Comment by huard** [comment]
Sometime `make html` goes through all the notebooks, and sometimes it doesn't. Confused as to what triggers this, but has a large impact on build time.

**Comment by Zeitsperre** [comment]
This isn't well documented, but it's due to an environment flag-based workaround I added to help with speeding things up:

https://github.com/Ouranosinc/xclim/blob/f8c3abe975a408c51c0b8eb172982d7fd342eca1/docs/conf.py#L215

If your shell has `SKIP_NOTEBOOKS` defined, the notebooks will not be run. For ReadTheDocs, the notebooks will conditionally be run (auto/always) depending on whether the trigger was coming from a pull request or from main.

This should be made much clearer in the contributing documentation at the very least.
