### ISSUE TITLE
AttributeError: 'Dataset' object has no attribute 'get_axis_num' When use xclim.core.calendar.percentile_doy

### ISSUE THREAD

**Issue by CGL5230** [Ouranosinc/xclim#1521]
### Generic Issue

Hi,all
 I got a error when I try to use the `xclim.core.calendar.percentile_doy `to calculate the R95P.

Here is the information for the dataset. It's daily precipitation of the CMIP6.
![image](https://github.com/Ouranosinc/xclim/assets/57136380/74fcf633-b817-4dce-ac43-772f661840ef)

I used the following command to calculate the R95P, but the frist line got error as I mentioned.
`ssp126_p95 = xclim.core.calendar.percentile_doy(pr_AWI_CM_ssp126,per=95)`
`AWI_CM_ssp126_R95P = xclim.indicators.icclim.R95p(pr='pr',pr_per=ssp126_p95,freq='YS',ds=pr_AWI_CM_ssp126)`
![image](https://github.com/Ouranosinc/xclim/assets/57136380/c25e1124-9a9b-4ca2-9369-c6046a43bec2)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CGL5230** [comment]
I maybe know the issue... THE dataset I used don't choose the variable 'pr'.

But I got other question: I calculate the percentile_doy is very long time cost. Any idea?

**Comment by aulemahal** [comment]
Indeed, the initial issue might simply be that you are passing the dataset instead of the variable directly. Usually in xclim functions, when a variable is expected, the `DataArray` should be passed. I suggest you do the same for the second line, simply for clarity.

```python3
ssp126_p95 = xclim.core.calendar.percentile_doy(pr_AWI_CM_ssp126.pr ,per=95)
AWI_CM_ssp126_R95P = xclim.indicators.icclim.R95p(pr=pr_AWI_CM_ssp126.pr, pr_per=ssp126_p95, freq='YS')
```

As for the performance, the `percentile_doy` process is indeed a bit heavy and your dataset is large. I see you are not using `dask` to parallelize the compuation, that's the first step I would recommend to accelerate the process. The data preparation happens at the xarray-level, but xclim is meant to be fully compatible with dask array. Xarray has a page to explain how it works : https://docs.xarray.dev/en/stable/user-guide/dask.html
