### ISSUE TITLE
Calculate R95P for the specified threshold

### ISSUE THREAD

**Issue by CGL5230** [Ouranosinc/xclim#1570]
### Setup Information

- Xclim version:0.47
- Python version:3.11
- Operating System:Linux

### Context

Hi,all!

I downloaded the daily average precipitation dataset from 2015-2100Cmip6. the R95P in Xclim is to calculate the 95% quantile for a given time period (if I understand correctly).

I want to know if the R95P for 2085-2100 has increased compared to the R95P for 2015-2030. **This means to set the 95% quantile for 2015-2030 to a fixed threshold**,to calculate the R95P for the period 2015-2030, 2085-2100. Because the threshold for heavy rain may be easier at 30mm, but reaching 60mm is difficult.

Now, I calculate R95P is like below:
```
TaiESM1_ssp126_p95 = xclim.core.calendar.percentile_doy(pr_TaiESM1_ssp126.pr,per=95,window=5)
TaiESM1_ssp126_R95P = xclim.indicators.icclim.R95p(pr='pr',pr_per=TaiESM1_ssp126_p95,freq='YS',ds=pr_TaiESM1_ssp126)
```
I think this is equivalent to calculating the 95% quartile over the course of a year.This means that the values of the 95% quantile will be inconsistent in both 2015-2030 and 2085-2100.
Can I calculate it like this? In order to achieve my goal above.Maybe there is an easier way?
```
TaiESM1_ssp126_2015-2030_P95 = xclim.core.calendar.percentile_doy(pr_TaiESM1_ssp126_2015-2030.pr,per=95,window=5)
TaiESM1_ssp126__2015-2030_R95P =xclim.indicators.icclim.R95p(pr='pr',pr_per=TaiESM1_ssp126_2015-2030_p95,freq='YS',ds=pr_TaiESM1_ssp126_2015-2030)
TaiESM1_ssp126__2085-2100_R95P =xclim.indicators.icclim.R95p(pr='pr',pr_per=TaiESM1_ssp126_2015-2030_p95,freq='YS',ds=pr_TaiESM1_ssp126_2085-2100)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coxipi** [comment]
Hi! 

I think that stating "R95P for 2085-2100 has increased compared to the R95P for 2015-2030" is an ambiguous precisely because they are defined with reference to a `p95'.  I think both of your suggestions can give some information on this, it just gives different measures.

1. Your first suggestion, you have 
```
`p95_2015-2030, pr_2015-2030` -> `rp95_2015-2030`
`p95_2085-2100, pr_2085-2100` -> `rp95_2085-2100`
```
In both cases `rp95_2015-2030` and `rp95_2085-2100`, values should over around 5% * 365 days ~ 18.25. But, by comparing both periods, you would see perhaps more variability in one period or the other, i.e. from year to year, are there bigger gaps with respect to the 95th quantile in each respective period.

2. You second suggestion, you fix `p95_2015-2030`
```
`p95_2015-2030, pr_2015-2030` -> `rp95_2015-2030`
`p95_2015-2030, pr_2085-2100` -> `rp95_2085-2100`
```
So, if the difference `rp95_2085-2100 - rp95_2015-2030`  is skewed towards positive values, then, for example, you find out that bigger values are more frequent in the future. This is probably what you want?

I'm not too familiar with this kind of computation, so I'm not sure what possibility you're interested in: case 1?, case2? unexplored case3? Do you have an article in mind that does this kind of comparison you could share?

As for the actual implementation, I think what you do it OK and simple, I see no problem there.

**Comment by CGL5230** [comment]
Yes! I try to use case2 to explore the change of R95p for SSP paths. I see the improtance to keep an unchange reference date that let the R95p right.
