### ISSUE TITLE
ExtremeValues returning all nan results

### ISSUE THREAD

**Issue by bweeding** [Ouranosinc/xclim#1775]
### Generic Issue

* xclim version: 0.47.0

I'm attempting to implement sdba.adjustment.ExtremeValues to adjust extremes in some rainfall data, and while it appears to be generating a valid adjusting object, when I use it to adjust the historic data I trained it on, I receive an all nan result. The data is particularly difficult as typical hist rainfalls are much lower than ref, except for one incident of very heavy rainfall.
![Untitled](https://github.com/Ouranosinc/xclim/assets/57697604/05298362-4807-44c6-8e6f-154a2046d8e0)

```
# set the grouping object
qdm_group = sdba.Grouper("time.dayofyear", window=31)

# jitter the rainfall data to avoid zero issues
hist_jit = sdba.processing.jitter_under_thresh(hist_data, "0.01 mm d-1")
ref_jit = sdba.processing.jitter_under_thresh(ref_data, "0.01 mm d-1")

# train the adjusting object
QM_ad = sdba.QuantileDeltaMapping.train(
    ref_jit,
    hist_jit,
    nquantiles=100,
    kind="*",
    group=qdm_group
)

# perform the adjustment
hist_adj = QM_ad.adjust(hist_jit)
```
This works quite well given the challenging data.
![Untitled-1](https://github.com/Ouranosinc/xclim/assets/57697604/5b89999d-ad2f-4878-9b19-254c9f48cf68)

However, when I come to adjust the extremes, I end up with hist_adj_ex full of nans.
```
ex_ad = sdba.adjustment.ExtremeValues.train(ref=ref_data,hist=hist_data,q_thresh=0.99,cluster_thresh='1 mm/day')

hist_adj_ex = ex_ad.adjust(sim=ref_data,scen=hist_adj)

all(np.isnan(hist_adj_ex))

True
```
I can't tell where I'm going wrong - a threshold value of ~30mm/day seemed sensible to me, but perhaps I've chosen the inputs incorrectly?

I've attached the data in netcdf files in the zip.

Cheers
Ben

[extremevalues_data.zip](https://github.com/user-attachments/files/15784098/extremevalues_data.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coxipi** [comment]
Hi! Thanks for this report and the inclusion of your data, it's very helpful for troubleshooting. I'm unsure if this is type of behaviour is expected since your datasets are too different, or it's an error in the coding of the function: I will try to check this in more details later. But here are two quick observations: 
* It's the fitting of `hist` that fails and returns only NaNs, then this propagates to adjustment factors
* With `q_thresh=0.9`, I see that the fitting works. 

@juliettelavoie @RondeauG are more familiar with this function and maybe can help.

**Comment by RondeauG** [comment]
@coxipi covered it well. I see a few issues with your use case:

1. The Pareto distribution is built using values greather than `q_thresh`, where the actual threshold in millimiters will be the average of the `q_thresh` quantile computed for `ref` and `hist`(the raw one, not `hist_adj`). Your values in `hist` are much smaller than `ref`, so this approximation failed when you used `q_thresh=0.99`. If it gave you for example a threshold of ~25 mm (as the average of ~45 mm and ~5 mm), then this threshold was greater than all of your values in `hist`. The NaN is simply because no data was available to build the Pareto distribution.

2. There is clearly something strange with your `hist` timeseries, as the values are much smaller than your reference dataset. Either the units are wrong and a transformation needs to be applied before calling `xclim.sdba`, or your simulated data isn't quite adequate at that location. If it's the latter, even if bias correction can help from a statistical standpoint (as `QuantileDeltaMapping` did), I would take a step back to assess whether the data can be trusted or whether it needs to be discarded.

3. Linked to my second point: the 200 mm precipitation in `hist` looks very suspicious to me. I've seen that kind of distribution before and in most cases, this came from a bug in the climate model ("gridcell storm") or similar errors. See for example Figures 7 and 12 of [this report](https://www.ouranos.ca/sites/default/files/2023-03/proj-201419-post-traitement-projections-510035-rapport-technique.pdf) (in French).

4. A smaller detail, but in `hist_adj_ex = ex_ad.adjust(sim=ref_data,scen=hist_adj)`, it should be `sim=hist` or `sim=some_future_data`. `ref` is used during the training step to build the correction function, but isn't used after.

**Comment by coxipi** [comment]
I think @RondeauG has given an appropriate answer, so I will be closing the issue unless you have something to add @bweeding?

**Comment by bweeding** [comment]
Ah yes sorry, please go ahead and close. Thanks for the responses!
