### ISSUE TITLE
__version__ is not up to date

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#202]
### Description

The master's version is set to 0.8-beta, which is confusing since a lot a changed since then. We need to set up a mechanism for` __version__` to reflect the actual state of the code.

**Comment by Zeitsperre** [comment]
Once we are able to update our documentation (see: #159 and #163) and add release notes for v0.8-beta and now v0.9-beta (@tlogan2000), we can start strictly using semantic versioning for all pull releases to master.

**Comment by huard** [comment]
Why is this conditional on #159 and #163 ?

**Comment by tlogan2000** [comment]
I'm hoping to get to the release notes early next week.  I think the docs for the subset and ensembles packages should be straight forward .

**Comment by Zeitsperre** [comment]
@huard @tlogan2000 

The idea is primarily to have consistent release notes and full documentation so we can tag the next version as a v1.0 release candidate. From there. we would be adding documentation with every push to master branch so that we have clearly defined changes between versions. #159 and #163 would catch us up on recent changes for the past 3-4 months and since there's roughly only been 6-7 major pushes to master, it shouldn't be too bad.

I'll be back at this this coming week. Would you be up for chatting Wednesday or Thursday on a game plan as we move towards v1.0?

**Comment by huard** [comment]
I think it's premature to issue a 1.0 release. I would like to see things settle down a bit before we freeze the API, get better at semantic versioning, adding indicators, some bias-correction algorithms, etc.

**Comment by Zeitsperre** [comment]
Ok, sounds good. In that case, all we need to do is ensure that the version gets bumped whenever we push to `master`. For reference, the procedure is as follows:
```
$ git add * && git commit
$ bumpversion minor
$ git push
$ git push --tags
```
We also need to ensure that changes to the release notes are performed before we push. The responsibility should be up to the reviewer.
