### ISSUE TITLE
Implement `subset_polygon` function

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#278]
### Description

Create a function that takes as input a single polygon and a xarray.Dataset/xarray.DataArray and returns a cropped dataset/dataarray over the polygon, with masked values outside the polygon.

**Comment by tlogan2000** [comment]
I think there has been some miscommunication here I thought that this type of discussion had already taken place and had more or less indicated to @Zeitsperre to try to go forward with the methodology using geopandas seen in #285 

I suggest taking a step back:

Here is a list of potential libraries that can subset polygons:
* rioxarray
* geoxarray
* xgeo
* regionmask
* rasterx

@Zeitsperre before continuing with #285 (beyond the couple tests you had almost finished) I think we could all use some summary knowledge on what the capabilities of each of these packages are in terms of the following use cases (@huard @Zeitsperre @RondeauG  feel free to add to the list that I might of forgot)

* Reprojection capabilities - Handling all positive longitudes 

* Reprojection capabilities - Edge case of above : handling prime meridian crossing. E.g. when polygon crosses 0 deg lon but ds longitude values are all positive.  With #285  we saw that we need to split the polygon in order to subset properly. How/can other libraries deal with this?

* Curvilinear lat/lon grids - Can these libraries handle subsetting of rotated pole data such as CRCM5

* Multipolygon geometries - Can the input shape be a Multipolygon? Note this was my main reason for employing the spatial-join method recycled in #285 

* Grid Centroids not in polygon : The polygon is small enough that not grid centroids are fall within it.  Can it detect gridcells that intersect (e.g. lon/lat bounds) or use a buffer as suggest

* Could #285 pass these other libraries' test suites?

**Comment by huard** [comment]
I'd add to that 
* user interface (how intuitive/user-friendly is the interface to subset a Dataset ?)

**Comment by Zeitsperre** [comment]
Fixed with #285
