### ISSUE TITLE
Fit distributions using L-moments in addition to ML

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#33]
We should be able to fit these six distributions using both maximum likelihood and the method of L-Moments:

- [ ] Gumbel (right)
- [ ] GEV
- [ ] LogNormal2 (loc=0)
- [ ] LogNormal3
- [ ] Pearson type III
- [ ] Log-Pearson type III 

This new functionality would be exposed in `indices.generic.fit`, `fa` and `frequency_analysis` as a new parameter `estimator` taking the default value `ml` for the default scipy ML estimator, and `lmom` for L-moments estimator.

**Comment by monocongo** [comment]
In case it's helpful I thought I'd mention that I was able to eliminate quite a bit of my project's code for L-Moments used for Pearson Type III by instead using the [lmoments3](https://github.com/OpenHydrology/lmoments3) package. I'm not sure if this would work for you guys since you're so wedded to xarray/dask -- I think it's all in numpy, and this may prove to be a deal breaker for xarray/dask if there are any loops, etc. therein which [dask doesn't handle well/at all](https://stackoverflow.com/questions/52933553/dask-assignment-error-when-updating-a-value-in-a-dask-array-using-typical-numpy).

**Comment by huard** [comment]
Thanks for the tip ! I'm not too worried about dask at this point, as long as we can apply a function to a 1D array, we should be good. Can you confirm that lmoments3 uses the same parameters as scipy.stats ? That is, if I fit a distribution with scipy.stats' ML and lmoments -LMOM, I'll get comparable arrays of parameters ?

**Comment by monocongo** [comment]
I'm not sure about the package you're referring to in scipy.stats, David. Several years ago I rolled my own versions of L-moments and Pearson Type III fitting/cdf etc. based on some Fortran code I was replacing. My assumption is that the code in lmoments3 is more robust, and by using it I can reproduce the results of the previous PE3/L-Moments implementation I had in place. However, I wasn't aware that there is a comparable set of functions in scipy.stats, and if so my preference would be to use that package instead of lmoments3 since it's more of a quasi-standard library, more likely to be maintained, etc. If you're already using scipy.stats for L-Moments etc. for Pearson Type III then I can't think of a reason to use lmoments3 instead (and I'd like to know if so, as I will likely follow your example).

In case it helps to put things into context the code where I'm using lmomemts3 is [here](https://github.com/monocongo/climate_indices/blob/master/climate_indices/compute.py#L152).

**Comment by huard** [comment]
@sbiner Possible pour toi de m'aider à prendre les indicateurs dans https://github.com/Ouranosinc/raven/blob/FrequencyAnalysis/raven/utilities/indicators.py
et convertir ça en indicateurs xclim ? J'aimerais avoir une sorte de fonction générique paramétrisable plutôt qu'une liste de fonctions presque identiques.

**Comment by sbiner** [comment]
@huard oui c'est possible. J'ai fait le tour du code dans ta branche streamflow et beaucoup de choses m'échappent pour l'instant. Peux-tu ajouter un test afin que je vois un peu de quoi tu voudrais que ça ait l'air et comment vérifier que le résultat est tel qu'attendu.

**Comment by huard** [comment]
10-4, je te fais ça aujourd'hui.

**Comment by sbiner** [comment]
Est-ce qu'il y a des nouvelles dans ce dossier @huard?

**Comment by huard** [comment]
lmoments3 does not seem to be maintained anymore. One options would be to get lmoments code into scipy.stats.

**Comment by huard** [comment]
See https://github.com/scipy/scipy/issues/11782
