### ISSUE TITLE
Add CF-Conformance methods

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim#350]
Following the discussion raised in #348 

It would be interesting and remarkably useful if there were a means to examine an xarray object's attribute and coordinate mappings and be able to perform the following:
- Ascertain whether the object is in conformance with Climate and Forecast (CF-)conventions
- If the data doesn't follow conventions, 
    - Perform mapping changes directly on the data (perhaps based on mappings hard-coded from conventions used by the data sources, e.g. ECMWF, ESGF) to make the data adhere more to CF-conventions. 
    - Save these changes in a dictionary or XML/ncML file that is associated to the files (not touching the data itself).

This requires use some new libraries (`lxml` to create and build out XML/ncML chains, a CF-checking library to evaluate data conformance and return a dictionary of fixable errors?) that would need to be looked into.

Potential implementations:
- Write a function that performs basic checks (hard-coded by us) or a more involved check using an additional library.
- Extend the xarray.DataArray or xarray.DataSet object to add a `to_cf` method that performs the checks above and calls necessary changes.
- Have the method include an "use_ncml" flag to specify whether the method returns a new file with modified fields or an ncML that would perform said modification.

This might be difficult to test with xarray at the moment, seeing as reading of ncML files is not presently implemented. Advice and ways forward on this are encouraged.

**Comment by huard** [comment]
I think this issue is too ambitious. 

My suggestion would be to remove: 

* Perform mapping changes directly on the data (perhaps based on mappings hard-coded from conventions used by the data sources, e.g. ECMWF, ESGF) to make the data adhere more to CF-conventions.
* Save these changes in a dictionary or XML/ncML file that is associated to the files (not touching the data itself).

because this is the essence of the c3s 34e project.

I suggest we restrict ourselves to `Ascertain, in the test suite, whether xclim **output** is in conformance with Climate and Forecast (CF-)conventions using an existing library`.
