### ISSUE TITLE
crs coordinate added during the `subset_shape` call

### ISSUE THREAD

**Issue by davidcaron** [Ouranosinc/xclim#396]
* xclim version: 0.15.0
* Python version: 3.8
* Operating System: ubuntu

### Description

This happened in the finch test suite: https://github.com/bird-house/finch/pull/107/commits/7f5ffff1ed422df8ddd12286f5990cf3fbe389c2

When I call `xclim.subset.subset_shape`, a 'crs' coordinate is added to the dataset: https://github.com/Ouranosinc/xclim/blob/a838560caa6b03678dbd1a25799f5fb8b562f9f4/xclim/subset.py#L560

However, when writing the dataset to disk, I get this error: 

```
File ".../python3.8/site-packages/xarray/backends/api.py", line
205, in check_attr
    raise TypeError(
TypeError: Invalid value for attr: +proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs lon_wrap=180 +type=crs must be a number, a string, an ndarray or a list/tuple of numbers/strings for serialization to
netCDF files
```

For now, I just dropped this coordinate in finch...

**Comment by huard** [comment]
@Zeitsperre crs dict should be jsonified. Points to a gap in the test coverage.

**Comment by Zeitsperre** [comment]
@huard The format above is a PROJ4 string (an older, but universally recognized format for CRS in Java, Python, GeoServer, QGIS, etc.). I figured a coord would be fine, but had no idea it would present a problem with CF compliance.

When considering the guidelines presented in the CF-Conventions, it appears that there's a lot of work to do here: http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#appendix-grid-mappings

In order to make this properly, I need to take the Proj4 and convert to WKT, then parse out the relevant fields into a variable that adheres to conventions: http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#grid-mappings-and-projections.

I can start on this this week. In the meantime, I can push a hotfix that moves the Proj4 CRS into a global attribute (not conventional, but at least not breaking xarray).

**Comment by huard** [comment]
@Zeitsperre 
:+1: for the hot fix. 

For a full solution, I suggest first doing a review. It seems pyproj has something along these lines. https://pyproj4.github.io/pyproj/v2.2.0rel/api/crs.html?highlight=to_cf#pyproj.crs.CRS.to_cf
