### ISSUE TITLE
sdba - improve the speed of DetrendedQuantileMapping

### ISSUE THREAD

**Issue by RondeauG** [Ouranosinc/xclim#455]
### Description
Doing a few preliminary tests **on a single pixel and without dask**, I obtained the following times : 

DetrendedQuantileMapping, groups='month', 150 years of daily data : ~15 seconds
DetrendedQuantileMapping, groups='day', window=31, 150 years of daily data : ~24 seconds

EmpiricalQuantileMapping, groups='month', 150 years of daily data : ~0.35 seconds
EmpiricalQuantileMapping, groups='day', window=31, 150 years of daily data : ~2.5 seconds

There seems to be a bottleneck in the detrending version. Discussions with @aulemahal point towards the normalization process and `sdba.utils.interp_on_quantiles`. I will continue investigating and post my findings here.

**Comment by aulemahal** [comment]
To clear out my thoughts: 
- The normalization process, as all non-grouping grouped operations, has additional overhead because it needs to resort the data along the time axis. And to rechunk if dask is used.
- `interp_on_quantiles` currently calls griddata through a _vectorized_  `xr.apply_ufunc`, which is far from optimal. Vectorization is a siimple for-loop, and `apply_ufunc` forbids chunks along the main dim (here 'time'). Getting rid of both would be a great improvement.
- Also, because of #442, DQM has 2 extra operations that would disappear were that issue to be fixed.

To compare, when calling train+adjust, here is the number of "operations" that the data goes through:

- EQM: 3 (quantile / correction / interpolation)
- DQM: 11 (2x normalization, 3x correction, detrending (fit + correction), retrending + EQM) (Fixing 442, would remove 1 normalization and 1 correction)

So we expect a longer computation time, but maybe not that much.

**Comment by RondeauG** [comment]
The issue seems smaller than I previously thought. While it does take a long time to bias correct a single pixel, the script seems very scalable.

So while it can take as long as 70 seconds to bias correct a single pixel and save it to NetCDF, I managed to bias correct 14 375 pixels, 1/3rd of Canada, in 441.52 seconds (0.0307 seconds per pixel).

This is still something that could be explored for a future enhancement, but this is not a priority.
