### ISSUE TITLE
Notebook outputs in docs

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#490]
* xclim version: master

### Description

- The cell outputs from notebooks are not rendered by the sphinx documentation on readthedocs. 
- The `pint` link is malformed in the units notebook once rendered by sphinx.

**Comment by aulemahal** [comment]
This was a problem in 0.17 (and 0.16?) because we merged (by mistake) a PR that was settiing the sphinx notebook execution to "never". I believe that PR #472 fixed that. The notebook outputs are generated on the "latest" branch in readthedocs, which I believe is the master? (@Zeitsperre ?) 
I believe that publishing a new version will update the "stable" branch and thus reactivate the notebook execution.

**Comment by huard** [comment]
I think sphinx has options to 
- render notebooks with pre-existing outputs
- render notebooks by running the notebooks
  - with outputs
  - without outputs

So using execution to never does not (I believe) imply that outputs are not rendered. 
The build on readthedocs is failing at the moment.

**Comment by aulemahal** [comment]
As far as I understand, the current setting  `nbsphinx_execute = "auto"` means that the notebook is executed only if not output is already present. As we have the  `nbstripout` git hook enabled, each commit strips the output except in cells where `"keep_output": true` has been manually inserted.  So it is this setting, indirectly, that controls our notebook execution.

As for the failing build on Read the docs, I'm not sure how to look into this? Where do we see the log and the failure state?

**Comment by huard** [comment]
I was not aware of this hook, and I think it is a problem, because we probably don't want to have to run the notebooks on readthedocs. Register on readthedocs and send me your ID, I'll make you a maintainer.

**Comment by aulemahal** [comment]
Reopening because I believe we need to make a decision.

I personally like the nbstripout git hook because the machine-dependent metadata gets written to ipynb files whenever they are run,  adding a lot of noise to the PRs. Moreover, executing them during the build process helps assure that the doc is up-to-date.
So I would keep the current system: nbstripout + nbsphinx='auto' + deactivating execution with `"keep_output"=true`.

The alternative (what we had before) would be to _never_ execute the notebooks. This requires everyone who edits them to be sure that the notebook is good to be put on readthedocs as-is when committing changes. We could force the execution in one of the test builds, but that wouldn't affect read the docs.
