### ISSUE TITLE
Consecutive threshold spanning across intervals

### ISSUE THREAD

**Issue by pbreach** [Ouranosinc/xclim#505]
The climdex.pcic package provides options to specify whether indices that are computing consecutive days above or below a threshold can span across that interval. For example: https://rdrr.io/cran/climdex.pcic/man/climdex.cdd.html using `spells.can.span.years` option allows for consecutive dry days spanning across two years to be counted and then assigned to the year in which the dry spell began

Is this something that would be useful to include here or is there a workaround in xclim? I wrote some code on this using itertools.groupby to break out all the consecutive days and then grouped into intervals in the past. Any thoughts on if a PR would be welcome for this?

**Comment by huard** [comment]
Hi @pbreach, 

A PR would certainly be welcome !

I *think* some of our utilities already support this, but maybe not all. This is something we've looked at in the past and I seem to remember we hit memory issues. xclim uses dask and so we need to create memory "halos" around each chunk to achieve this while preserving dask's parallelization. 

The relevant pieces of code are in `xclim/indices/run_length.py`. You'll see that some functions first create a `rolling` object that  spans across periods. Extending or improving on this concept for the indices that you're interested in would be appreciated.

**Comment by aulemahal** [comment]
I had a quick look at the problem and @huard is indeed right: the reason this is not implemented in xclim is because of high memory usage by the run length methods.

Right now for any "run length" method, xclim resamples (groups) the data to the requested frequency and then, on each groups, applies the method. Example with an "annual longest heat spell" returning the length of the longest series of consecutive days with tmax above a threshold:
1) Cut the data into years
2) Get the boolean array of tmax > thresh
3) resample to yearly groups 
For each group:
  4) Apply `run_length.rle`, which puts the length of a series of consecutive `True` at the start of that series.
  5) Get the max of that array.

In order to manage the spells spanning across periods we could invert 3 and 4, i.e.: apply `rle` on the whole dataarray and then resample and take the max of each group. However, even if `rle` is dask-ready and quite optimized, it uses more memory than the current way. Also, that change would need us to rethink the API a bit.

For reference, a graph comparing the two methods on generic test data:
![overlaps_midchunks](https://user-images.githubusercontent.com/20629530/88727504-c5ad6580-d0fd-11ea-8bc2-2e29908c0898.png)
(xc_default is the current method, "rle_resample" is what I described). In that example, data is made of 20 chunks of 730x100x100 (time, x, y), chunking is along "time".  Larger chunks make `rle` crash, and so does using a dask client in order to limit the memory usage (example uses the default scheduler).

Pros of adding the option:
- Capability of considering spells spanning across periods
- Chunks don't have to be multiples of the periods : right now, chunks along "time" must be a multiple of the period  or else it fails.

Cons:
- Complex implementation because the API needs to be partially redesigned, especially is we want to keep it a user's choice.
- Potential memory problem when using it. `rle` is not yet fully optimized and will crash on large datasets.
