### ISSUE TITLE
I'd like to reuse some of the testing utilities in Finch

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#601]
### Description

There are some useful utilities in xclim conftests. Is there a way to make them available to other libraries (e.g. Finch) ?

**Comment by Zeitsperre** [comment]
The only way I could see that is if the tests were bundled with xclim. Currently, they aren't. I can see a few ways of doing this:
- Fetch the file as part of the pre-install step for an image build (ie: wget from a raw github link)
- Set finch to install the source file version of xclim (not the wheel) and locally copy the conftest file from the installed xclim location to where you want it to be.
- Export xclim.testing to the xclim-testdata repo and it into an installable package (that either bundles the testing data or provides the wrapper to fetch the data.
- Throw out the configurations and make an intake catalogue for better portability.

Lots of potential solutions from my perspective...

**Comment by huard** [comment]
I'd like to propose including the tests inside the installation. This is what xarray does. 
In a related note, xarray and xESMF use an extremely simple setup.py 
```python
#!/usr/bin/env python
from setuptools import setup

setup(use_scm_version={"fallback_version": "999"})
```
And all the information is in the setup.cfg. This is something we could look into as well.

**Comment by Zeitsperre** [comment]
Placing the tests inside the package will require us to move the folder (`xclim/tests` -> `xclim/xclim/tests`), and perform a handful of changes to support it (mostly managing what is visible to `xclim` and `pytest`). It's feasible but it would require a bit of refactoring. One other option could be to create a very small helperpacking that installs the tests. I've performed a similar thing for PAVICS before https://pypi.org/project/requests-magpie/.

For the second point I'm confused. The reason we have such a more traditional setup.py layout is because of the cookiecutter approach. I don't see what the gains are for performing that on xclim (beyond adding a setup.cfg to the MANIFEST.in). If we are open to modernizing the setup.py, I would propose that we migrate to `pyproject.toml` files, as managing dependencies, publishing to PyPI, setting configurations, etc. are all handled out-of-the-box with that.

**Comment by huard** [comment]
Let's ignore the second point, sorry I introduced that, let's discuss this is in another issue. 

Just moving tests inside of xclim sounds to me like the simplest solution, no ? What are the drawbacks ?

**Comment by Zeitsperre** [comment]
None, really. I took some time to think it over and it would make much more sense. Presently, the only way to test xclim is to collect the source files or to clone the git repo. We packaged it this way because of the large size of the test data.

Now that the test data has been moved out of the library, there really isn't much to stop us from packing the tests alongside the code in wheel format. It shouldn't take very long to do. Priority level?
