### ISSUE TITLE
Multivariate quantile mapping bias correction implementation

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#603]
Implement https://link.springer.com/article/10.1007/s00382-017-3580-6

**Comment by Paattrriicckk** [comment]
Si vous voulez implémenter la méthode de Cannon, l'article suivant pourrait vous intéresser, puisque les auteurs (seticon 3.3.2) décrivent cette méthode en d'autres mots que ceux de Cannon : https://hess.copernicus.org/preprints/hess-2020-639/hess-2020-639.pdf.

Van de Velde et al. (under review) Impact of bias nonstationarity on the performance of uni- and
multivariate bias-adjusting methods.

**Comment by huard** [comment]
There is a reference implementation in R and another in Matlab from ETS we can draw inspiration from.

**Comment by aulemahal** [comment]
Les auteurs Van de Velde et al  ont rendu leur code public! https://github.com/h-cel/ImpactofBiasNonstationarity

**Comment by Paattrriicckk** [comment]
Excellent ! J'espère que leur article final associé à ce code sera lui aussi publié, pour qu'on voit leurs recommandations.

**Comment by aulemahal** [comment]
Oui j'ai vu! Pour le moment, je me base sur le preprint et l'article de Cannon.

**Comment by aulemahal** [comment]
Notes after my first read of Cannon: 
This will be really hard to run on dask because it relies on an indefinite number of iterations (N). By that I mean that having a train+adjust scheme would need the saving N adjustment factor matrices + N rotation matrices, which is enormous!
Merging the two would work, but writing a lazy version of the algorithm will be tricky!
