### ISSUE TITLE
`percentile_doy` hangs in long time slices with dask.

### ISSUE THREAD

**Issue by larsbuntemeyer** [Ouranosinc/xclim#693]
* xclim version: 0.25.0
* Python version: 3.9.2
* Operating System: x86_64 GNU/Linux

### Description
Hello! I am trying to compute climate indicators of CMIP6 that require the computation of running percentiles with `percentile_doy`. I parallelize data access using dask jobqueue with SLURM and I can compute simple climated indicators quite smoothly and fast. However, i run into problems using `percentile_doy` which makes the computation hang on the last bits. I'll attach my notebook screenshot with the dask progress bars...

![Screenshot 2021-04-15 at 23 24 07](https://user-images.githubusercontent.com/5659125/114940924-c419fe00-9e42-11eb-9263-44a520945766.png)

I can actually compute inicators like `TG` without problems and it's quite fase (about 5s). Also the `percentile_doy` starts quickly but hangs on the last `transpose` threads indefinitely... I am not sure, i tried different chunking and numbers of workers and threads but nothing worked smoothly. I am not sure, it's probably more a dask issue than an `xclim` issue. How do you handle longer time slices in `percentile_doy`? Thx a lot!

**Comment by larsbuntemeyer** [comment]
I just realized, i could solve this issue by using less workers and more threads, in my case i use now 6 workers and 8 threads per woker. So, it's definitely my fault! I reduced the reference period now to 1917-2000 and that runs smoothly in about 30s!

**Comment by aulemahal** [comment]
I am happy you found a solution! But this is an interesting problem, I most often ran into the inverse: computation with many threads and few workers would hang or simply be very slow. In that case, I believe this is due to some code in xarray/pandas that _locks_ the current process (in order to avoid race conditions, but maybe being a bit oversecure here). It's the first time I see the opposite. 
Throwing ideas: I suspect that dask's task hierarchy could be the culprit here. Like, two workers (say A and B) are given two lists of tasks (A := [t1, t2], B := [t3, t4]). Then if t1 depends on t3, but t3 depends on t2, it hangs, because each worker only has 1 thread, so only 1 task can be computed at the time.  This would mean we have an optimization bug on the side of dask.  But then again, simply using a few more threads solves it.
