### ISSUE TITLE
Compare outputs with icclim

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#71]
### Description

Include comparison of ICCLIM results into the tests. 

In particular, check how ICCLIM handles spells that last longer than the resampling period.

**Comment by huard** [comment]
ICCLIM does not seem to work out of the box with our files in testdata. It complains about missing _FillValue attributes or NETCDF4 format... Could we add a couple of test data files from CMIP5 (tasmin, tasmax, tas, pr) with a normal calendar ?

I've been able to run tests with ocgis however, and CFD (consecutive_frost days) yields the following results for calc_grouping ['month', 'year']: 
```
array([31., 28., 15., 23., 13.,  2.,  0.,  0.,  2.,  8., 27., 31.],
      dtype=float32)
```
which suggests that the array is resampled first, then the condition is evaluated. 

Integrating explicit ICCLIM tests is going to be a pain before the refactoring Xavier is doing. 
I suggest we close this issue and reopen it when ICCLIM is updated.

**Comment by Balinus** [comment]
From the tests I've done with ICCLIM I can say that it's a pain to work with. I had the same problem with subsetted files. 

I only succeeded in installing ICCLIM on python 2.7 also.

**Comment by Zeitsperre** [comment]
@huard Are we still interested in working on this issue?

**Comment by tlogan2000** [comment]
I would say no... but only because I have had too much trouble installing / running ICCLIM to make it a worthwhile endeavor.

**Comment by huard** [comment]
I've understood there is a new release of ICCLIM. Maybe worth checking.

**Comment by Zeitsperre** [comment]
Ideas:
- Open a ticket within https://github.com/cerfacs-globc/icclim about creating a new conda package?
- Install the newest version locally and create test data?
- @huard will open a channel with Christian Pagé about getting some test data from him?

**Comment by bzah** [comment]
I just stumble upon this issue and I will at some point do manual/semi-automated tests to compare icclim_v4 and xclim/icclim_v5.
However because icclim v5 will be based on Xclim it will not make much sense to fully automatize tests I think.

By the way if you have issues in installing/running icclim and still wish to do it, don't hesitate to ask me.

**Comment by huard** [comment]
Hi @bzah 

Do you have any updates? Are you far along in the comparison that you feel this issue can be closed?

**Comment by bzah** [comment]
Hello @huard, 
I just finish yesterday the report comparing icclim v5 (thus xclim) against icclim v4 and Climpact.
I'm expecting a last review from Christian before _officially_ sharing it.

The TL;DR is:
- Most indices work just fine.
- Indices relying on "consecutive days" have varying result due to #956. However it's not as bad as expected.
- Bootstrap algorithm is quite effective. See WSDI chapter for its effect.
- The computed percentiles are a bit different between the 3 software, but I could not find why.
- icclim v4 could generate some strange results, we are truly happy with what v5 has become thanks to xclim, xarray and dask.

If you want to have a look now, you can grab it on [icclim-sandbox](https://github.com/bzah/icclim-sandbox/releases) release along with all the figures in the zip file. 
Don't hesitate to create an issue there if you have any question or remarks.

**Comment by huard** [comment]
Went through your report, thanks for all the work ! 
I'll close this issue, but feel free to open issues to look into differences for specific indices.
