### ISSUE TITLE
anuclim indicator P8 and P9 return wrong Kelvin values

### ISSUE THREAD

**Issue by areichmuth** [Ouranosinc/xclim#762]
* xclim version: 0.27.0
* Python version: 3.8.10
* Operating System: Ubuntu 20.04

### Description
Hi, I used anuclim indicators (P8_MeanTempWettestQuarter, P9_MeanTempDriestQuarter) to calculate the mean temperature of wettest and driest quarters. As described in the code its been transformed to Kelvin, my input units are Celcius. As a comparison I also calculated the related index values. 

### What I Did
anuclim indicator calculation:
```
xclim.indicators.anuclim.P9_MeanTempDriestQuarter(tas=ds.tavg, pr=ds.pre, src_timestep='D')
```
Index calculation:
```
xclim.indices.tg_mean_wetdry_quarter(tas=ds.tavg, pr=ds.pre, op = 'driest', src_timestep = 'D', freq='YS')
```

### What I Received
My output values for the anuclim indicator range between -0.198 and 0.60 K which can't be true. Instead the index values return plausible Celsius values between -11.38 and 34.89 °C.

**Comment by tlogan2000** [comment]
Hello @areichmuth this behavoir is by design. XCLIM indicator calculations will ensure cf-compliant units and metadata are returned regardless of input temperature units.  CF conventions indicate K as the output unit https://cfconventions.org/.  To have units in Celsius there are a couple of options : 

Use `xclim.core.units` to convert output back to celsius for these calculations
````
from xclim core import units
units.convert_units_to(data, 'degC')
````

Alternatively you could explore the creation of a custom or personal version of these calculations (specifiying 'degC' as the output units) as in https://xclim.readthedocs.io/en/stable/notebooks/extendxclim.html#Indicator-creation or https://xclim.readthedocs.io/en/stable/notebooks/extendxclim.html#Virtual-modules

**Comment by tlogan2000** [comment]
Can you provide an output of the input data units?

**Comment by tlogan2000** [comment]
I think this might be the same issue as here in the end.  https://github.com/Ouranosinc/xclim/issues/741#issuecomment-858969304 

Sorry if you got a reply link to my deleted comment

**Comment by areichmuth** [comment]
Hi @tlogan2000 - thank you for your response. 
Here my input data units for the temperature DataArray:
```
<xarray.DataArray 'tavg' (time: 731, latitude: 168, longitude: 664)>
dask.array<open_dataset-4836d7104c08a7d039826eace4472410tavg, shape=(731, 168, 664), dtype=float32, chunksize=(731, 168, 300), chunktype=numpy.ndarray>
Coordinates:
  * time       (time) datetime64[ns] 1971-01-01 1971-01-02 ... 1972-12-31
  * longitude  (longitude) float64 20.27 20.3 20.33 20.36 ... 40.92 40.95 40.98
  * latitude   (latitude) float64 40.23 40.2 40.17 40.14 ... 35.08 35.05 35.02
Attributes:
    standard_name:  air_temperature
    long_name:      Bias-Adjusted Near-Surface Air Temperature
    units:          deg C
    cell_methods:   time: mean
    scaling:        1.0
```

**Comment by tlogan2000** [comment]
Ok yes it's as I thought try changing units 'deg C' to 'degC'  (no space) before calculating the indices to avoid `pint` interpreting units as "degrees * delta_degree_Celsius"
e.g.
```
ds['tavg'].attrs['units'] = 'degC'
xclim.indicators.anuclim.P9_MeanTempDriestQuarter(tas=ds.tavg, pr=ds.pre, src_timestep='D')
```

**Comment by areichmuth** [comment]
Perfect. That was the issue. Thank you.
