### ISSUE TITLE
`attrs['units']` required for `sdba`?

### ISSUE THREAD

**Issue by aaronspring** [Ouranosinc/xclim#811]
* xclim version: 0.28.3b0
(I am quite sure this worked in * xclim version: 0.28.2b)

### Description
Is a `units` required in variables to use `sdba`? I think this worked before without having units set, when units was something like `Celsius_scale`. My question is whether this units checking is always required or only required in a few occasions?

### What I Did

```python
import xarray as xr
import matplotlib.pyplot as plt

ds = xr.tutorial.load_dataset("rasm").isel(x=100,y=100)['Tair']

from xclim.sdba import EmpiricalQuantileMapping

reference = ds.isel(time=slice(None,12))
model = ds.isel(time=slice(12,24))
single_adjusted = EmpiricalQuantileMapping.train(reference, model, group='time').adjust(model) # works

del ds.attrs['units']
reference = ds.isel(time=slice(None,12))
model = ds.isel(time=slice(12,24))
single_adjusted = EmpiricalQuantileMapping.train(reference, model, group='time').adjust(model) # fails
```

### What I Received

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-11-8ae9e08d01bb> in <module>
     17 
     18 model.plot(label='model')
---> 19 single_adjusted = EmpiricalQuantileMapping.train(reference, model, group='time').adjust(model)

<boltons.funcutils.FunctionBuilder-594> in train(cls, ref, hist, **kwargs)

~/anaconda3/envs/climpred-dev/lib/python3.9/site-packages/xclim/sdba/base.py in _parse_group(*args, **kwargs)
    422             if not isinstance(kwargs["group"], Grouper):
    423                 kwargs = Grouper.from_kwargs(**kwargs)
--> 424         return func(*args, **kwargs)
    425 
    426     return _parse_group

~/anaconda3/envs/climpred-dev/lib/python3.9/site-packages/xclim/sdba/adjustment.py in train(cls, ref, hist, **kwargs)
    139             cls._check_inputs(ref, hist, group=kwargs["group"])
    140 
--> 141         hist = convert_units_to(hist, ref)
    142 
    143         ds, params = cls._train(ref, hist, **kwargs)

~/anaconda3/envs/climpred-dev/lib/python3.9/site-packages/xclim/core/units.py in convert_units_to(source, target, context)
    302         tu = target
    303     elif isinstance(target, (str, xr.DataArray)):
--> 304         tu = units2pint(target)
    305     else:
    306         raise NotImplementedError

~/anaconda3/envs/climpred-dev/lib/python3.9/site-packages/xclim/core/units.py in units2pint(value)
    144         unit = value
    145     elif isinstance(value, xr.DataArray):
--> 146         unit = value.attrs["units"]
    147     elif isinstance(value, units.Quantity):
    148         return value.units

KeyError: 'units'
```

**Comment by aaronspring** [comment]
You write in your CHANGELOG:

Add unit handling in sdba. Most parameters involving quantities are now expecting strings (and not numbers). Adjustment objects will ensure ref, hist and sim all have the same units (taking ref as reference).

What if no units given? Should that be allowed?

**Comment by aulemahal** [comment]
Hi! Sorry I could have tagged you in the other PR... 
So when we built xclim we made it so that units vital for its indices and indicators. Thus, we thought it didn't made sense to have a whole part of it, sdba, without any unit handling at all. And with the latest refactoring I thought this was the time to make this breaking change.

As for no units, this situation made no sense in the indices, for which the units submodule was created and thus there are no "workaround" currently for it in sdba.  Do you think it would be useful?  The workaround being simply plugging dummy units, like `ref.attrs['units'] = ""`.

The thing is, no attribute "units" does not mean the data has no units. For example: what if ref and hist had "K" units and sim comes in with no attribute. Should we assume it is in "K" too? What if the data really is in "degC"? As there is no way to know, I'd say I prefer the code to fail. But we have time to discuss that before the next release!

**Comment by aaronspring** [comment]
sounds plausible
