### ISSUE TITLE
User warning on cell_methods check when `area` is present

### ISSUE THREAD

**Issue by abel-bzz** [Ouranosinc/xclim#863]
* xclim version: 0.30.1
* Python version: 3.x
* Operating System: macOS

### Description

When using data where cell_method contains `area`, xclim raises a warning `cfchecks.py:39: UserWarning: Variable has a non-conforming cell_methods. Got "area: time: mean", expected "['time: mean*']"` (or equivalent).
For example, with `tas.cell_methods= area: mean time: mean`.

For reference, from [cf convention 1.9, chapter 7.3.1](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.pdf#%5B%7B%22num%22%3A543%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C0%2C210.159%2Cnull%5D):
>To  indicate  variation  over  horizontal  area,  it  is  recommended  that  instead  of  specifying  the
combination  of  horizontal  dimensions,  the  special  string  "area"  be  used.  The  common  case  of  an
area-mean can thus be indicated by cell_methods="area: mean" (rather than, for example, "lon: lat:
mean"). 

Would it make sens for Xclim to accept `area` in input variables cell_methods ?

**Comment by Zeitsperre** [comment]
Hey @bzah,

I wasn't familiar with that particular convention! It should absolutely be an acceptable input for cell methods, especially if we are working with lon/lat subsetted data. If you want to submit a PR, please tag me as reviewer.

**Comment by aulemahal** [comment]
Yeah... I find that cell methods are a bit tricky to process. The current code uses a glob-like pattern matching. Ex : `time: mean *`, which catches `time: mean within days` and other variations. It fails here because `area:` is _before_. But adding a * before would catch everything. That could be a solution, but if you think of a smarter way to check cell methods, @bzah, don't hesitate!
