### ISSUE TITLE
ENH: Add warning for visibly incoherent data before converting to Kelvin

### ISSUE THREAD

**Issue by bzah** [Ouranosinc/xclim#897]
* xclim version: 0.30.x

### Description
It could be interesting to make sure temperatures seem legit before doing unit conversion.
The user would probably appreciate a warning but not an error I think.

A pseudo code would be 
```
if tas[0]  <  -150ºC:  
  warning("the temperature analyzed is strangely cold (below -150ºC), make sure your input unit is consistent with your data")
```
Same could be done for hotness when data is in Kelvin but metadata is deg_C.

The only difficulty I see is to make the selection as cheap as possible but still avoiding NaNs.

### What I Did

I'm considering this because one of our beta user had a poorly written dataset where the metadata unit was "K" but the data was actually in "ºC". Thus by computing "SU" (T above 25ºC), xclim/icclim was giving a matrix of zeros.

**Comment by aulemahal** [comment]
I agree that it would be nice if we could tests for unphysical values on-the-fly, but, as you mentioned, the overhead for doing so is too expensive.

The tools you are looking for are in `xclim.core.dataflags` and can be run by the user before any computation for maximal safety. While implemented this, we decided against having it automatic in the `indicator` object because of the overhead.

It's not only NaNs and selection, but also with the dask-backend. A test like this would trigger data computation and we try to keep xclim indicators lazy.

**Comment by bzah** [comment]
Thanks @aulemahal,
You are completely right about Dask.

_Once again I forgot to check xclim doc before asking my question..._
