### ISSUE TITLE
Circular imports

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#949]
### Description

`core.missing` imports `indices.generic`, while some indices import `core.missing`, which causes circular import problems. 

The function required in `core.missing` is `select_time`. I suggest it is moved somewhere in `core/`, e.g. utils.py.

**Comment by aulemahal** [comment]
Not sure I understand where those circular imports are?
`missing` is imported by only one indice and it's down within the function, so that shouldn't cause the import error?

Currently, `snd_max_doy` fails on my end, but for another reason...

**Comment by huard** [comment]
In `indices._hydrology`, I have to do `from xclim.core.missing import at_least_n_valid` inside function definitions. If I try to do it at the top-level, it breaks.

**Comment by aulemahal** [comment]
I personally think it makes more sense to have `select_time` in `generic` than to import `missing` in `indices`. Because of our base division of indices vs indicators, missing value handling is supposed to be external to the indice computation. 
Like, I understand your use of `at_least_n_valid` as a clever trick more than a real dependency, no? You're not really "masking periods without at least N valid points".

**Comment by huard** [comment]
I guess what I mean is that select_time is a utility function, not a indice, and so should probably live in core. 

Correct, I'm using it to mask periods with no snow at all, so no doy is returned in those case.
