### ISSUE TITLE
cell_methods attribute is duplicated when computing indicator

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#983]
* xclim version: 0.31

### Description

If a DataArray has a cell_method, computing an indicator duplicates this cell_method before adding the indicator's own cell method. 

So for example if `da` has cell_methods `"time: mean within days"`, then computing `tg_mean(da)` we end up with something like
`time: mean within days time: mean within days time: mean over days`

**Comment by huard** [comment]
This is due to the fact that the indicator defines its cell method as 
`cell_methods="time: mean within days time: mean over days"`, so when input data is already daily mean with the proper cell_method, we have a repetition of `time: mean within days`. 

Why not just use `time: mean` here ?

**Comment by huard** [comment]
@tlogan2000 Are you behind this ? Thoughts ?

**Comment by aulemahal** [comment]
I see that `time: mean` would make sense for  `tg_mean`, but that implies overwriting the cell methods of the inputs. In most cases, this simplification doesn't happen  and we would rather _append_ the cell methods of the indice to the ones of the inputs. So instead of handling a special case I would suggest to appending.

As a result: 
For `tg_mean` on correctly formatted data, the new `cell_methods` would be `time: mean within days time: mean over days`.
For `tg_min`, on correctly formatted data, it would be `time: mean within days time minimum over days`.
For `tg_min` on data with missing attributes it would be `time: minimum over days`.

Unless we completely handle cell methods, which would be , I think, a complex hassle with low reward, I suggest sticking to what we do now, simply editing the `cell_methods` appended by existing indices.

**Comment by Zeitsperre** [comment]
Something I've started to come across that we'll need to consider (particularly in CMIP6) is the use of parentheses in `cell_methods` for newer CF-Conventions (see: https://cfconventions.org/cf-conventions/cf-conventions.html#recording-spacing-original-data). The method we choose to handle cell_method generation will need to take this into account.

**Comment by tlogan2000** [comment]
I think I would vote for the appending onto existing cell methods in general.  I like the interval parantheses from @Zeitsperre post as well. Much clearer in my mind.  Do we have already have tools to translate xarray `freq` values to a 'plain' language ?  
Something like : 
`da.attrs["cell_methods"] = f"{da.attrs["cell_methods"]} ; time: mean (interval:{prettify_freq(freq)})"`   seems like a pretty clean way to add cell methods (cleaner than what we have now anyway)
